Feature/kt-8. Refactoring KIP17Deploy
klaytn/klaytn-online-toolkit pull request #26
Opened 2022-11-01 01:27 UTC by edwin082

2022-11-01 01:42 UTC, skqksh commented
https://github.com/klaytn/klaytn-online-toolkit/pull/27
에 피드백 드린내용들과 유사한 부분 수정하고 코멘트 부탁드립니다

2022-11-01 04:10 UTC, edwin082 commented
> #27 에 피드백 드린내용들과 유사한 부분 수정하고 코멘트 부탁드립니다

@skqksh 피드백 주신 내용 반영해서 수정했습니다!

2022-11-02 01:06 UTC, skqksh approved these changes

2022-11-02 06:03 UTC, Yeonju-Kim requested changes

2022-11-02 06:03 UTC, Yeonju-Kim commented on src/views/SmartContract/KIP17Deploy.tsx
> +  Row,
사용하지 않는 imports 는 지워주셔도 될 것 같습니다.

2022-11-02 06:15 UTC, Yeonju-Kim requested changes

2022-11-02 06:15 UTC, Yeonju-Kim commented on src/views/SmartContract/KIP17Deploy.tsx
> +        setSenderDecryptMessage('')
setSenderDecryptMessageVisible(false)를 해주지 않아서 errormessage가 없어져도 cardsection이 그대로 남아있습니다.

2022-11-02 06:45 UTC, edwin082 commented
@Yeonju-Kim 코멘트 반영해서 커밋했습니다!

2022-11-02 07:50 UTC, Yeonju-Kim approved these changes

2022-11-02 07:51 UTC, merged